name: EDA-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - seaborn
  - warnings
conda activate EDA-environment
conda env export --from-history -f environment.yml
